services:
  kiro2cc-proxy:
    # 使用国内镜像
    image: ghcr.io/${IMAGE_OWNER:-tsinhzl}/kiro2cc-proxy:${IMAGE_TAG:-latest}
    container_name: kiro2cc-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "0.0.0.0:5678:5678"
    volumes:
      - ./data:/app/config
    restart: unless-stopped
